<script setup lang="ts">
import type { Summary } from '~/types/finance'
const finance = useFinance(); const selectedMonth = ref(new Date()); const summary = ref<Summary>({ income:0, expense:0, net:0, categories:[] }); const loading = ref(false); const money = (value:number) => new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB'}).format(value); const monthLabel = computed(() => new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(selectedMonth.value)); const maxCategory = computed(() => Math.max(...summary.value.categories.map(item => item.amount),1))
async function load() { loading.value=true; const start=new Date(selectedMonth.value.getFullYear(),selectedMonth.value.getMonth(),1); const end=new Date(selectedMonth.value.getFullYear(),selectedMonth.value.getMonth()+1,1); try { summary.value=await finance.getSummary(start.toISOString(),end.toISOString()) } finally { loading.value=false } }
async function move(offset:number){selectedMonth.value=new Date(selectedMonth.value.getFullYear(),selectedMonth.value.getMonth()+offset,1);await load()}
onMounted(load)
</script>
<template><main class="page"><div class="eyebrow">A clearer month</div><h1 class="display">Summary.</h1><section class="month-switcher"><button class="month-arrow" @click="move(-1)">←</button><div class="month-current"><span class="month-kicker">Viewing</span><strong>{{ monthLabel }}</strong></div><button class="month-arrow" @click="move(1)">→</button></section><div class="grid-2"><section class="card"><span class="muted">Money in</span><strong class="stat-value positive">{{ money(summary.income) }}</strong></section><section class="card"><span class="muted">Money out</span><strong class="stat-value">{{ money(summary.expense) }}</strong></section></div><section class="card net-card"><span class="muted">Net this month</span><strong class="stat-value" :class="{ positive: summary.net >= 0 }">{{ money(summary.net) }}</strong></section><div class="section-head"><h2 class="section-title">Where it went</h2><span class="muted">{{ loading ? 'Loading…' : `${summary.categories.length} categories` }}</span></div><section v-if="summary.categories.length" class="card category-list"><div v-for="item in summary.categories" :key="item.category" class="category-row"><span>{{ item.category }}</span><span class="amount">{{ money(item.amount) }}</span><div class="category-bar" :style="{ width: `${(item.amount/maxCategory)*100}%` }"></div></div></section><div v-else class="empty">No expenses in this month.</div></main></template>

