<script setup lang="ts">
import type { Summary } from '~/types/finance'
const finance = useFinance(); const { user } = useAuth(); const selectedMonth = ref(new Date()); const summary = ref<Summary>({ income: 0, expense: 0, net: 0, categories: [] }); const money = (value: number) => new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB' }).format(value)
const monthLabel = computed(() => new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(selectedMonth.value)); const isCurrentMonth = computed(() => selectedMonth.value.getFullYear() === new Date().getFullYear() && selectedMonth.value.getMonth() === new Date().getMonth())
const recent = computed(() => finance.transactions.value.slice(0, 5));
async function loadSummary() { const start = new Date(selectedMonth.value.getFullYear(), selectedMonth.value.getMonth(), 1); const end = new Date(selectedMonth.value.getFullYear(), selectedMonth.value.getMonth()+1, 1); summary.value = await finance.getSummary(start.toISOString(), end.toISOString()) }
async function moveMonth(offset: number) { selectedMonth.value = new Date(selectedMonth.value.getFullYear(), selectedMonth.value.getMonth()+offset, 1); await loadSummary() }
onMounted(async () => { if (user.value?.role === 'super_admin') return navigateTo('/admin'); await finance.refresh().catch(() => undefined); await loadSummary().catch(() => undefined) })
</script>
<template><main class="page ledger-page"><header class="ledger-header"><div><div class="eyebrow">Personal ledger</div><h1 class="display">Every balance,<br>in its place.</h1></div><NuxtLink to="/settings" class="avatar">{{ user?.username.slice(0,2).toUpperCase() }}</NuxtLink></header><section class="month-switcher"><button class="month-arrow" @click="moveMonth(-1)">←</button><div class="month-current"><span class="month-kicker">Viewing</span><strong>{{ monthLabel }}</strong></div><button class="month-arrow" :disabled="isCurrentMonth" @click="moveMonth(1)">→</button></section><section class="balance-card"><div class="balance-label">Across your accounts</div><div class="balance">{{ money(finance.totalBalance.value) }}</div><div class="balance-meta"><span><strong class="positive">{{ money(summary.income) }}</strong>money in</span><span><strong>{{ money(summary.expense) }}</strong>money out</span></div></section><div class="actions"><NuxtLink to="/transactions/new" class="action"><b>+</b>Add entry</NuxtLink><NuxtLink to="/transfers/new" class="action"><b>↔</b>Move money</NuxtLink><NuxtLink to="/accounts" class="action"><b>▤</b>Accounts</NuxtLink><NuxtLink to="/summary" class="action"><b>∑</b>Summary</NuxtLink></div><div class="section-head"><h2 class="section-title">Recent entries</h2><NuxtLink to="/transactions" class="text-link">All history →</NuxtLink></div><div v-if="finance.error.value" class="notice error">{{ finance.error.value }}</div><section v-if="recent.length" class="transaction-list"><NuxtLink v-for="item in recent" :key="item.id" :to="`/transactions/${item.id}`" class="transaction"><div class="transaction-icon">{{ item.category.charAt(0) }}</div><div class="transaction-copy"><strong>{{ item.title }}</strong><small>{{ item.accountName }} · {{ item.category }}</small></div><span class="amount" :class="{ positive: item.type === 'income' }">{{ item.type === 'income' ? '+' : '−' }}{{ money(item.amount) }}</span></NuxtLink></section><div v-else class="empty"><strong>Your ledger is ready.</strong><p class="muted">Add the first entry to begin.</p><NuxtLink to="/transactions/new" class="button accent">Add entry</NuxtLink></div></main></template>

