<script setup lang="ts">
import type { TransactionType } from '~/types/finance'
const route = useRoute(); const finance = useFinance(); const item = computed(() => finance.transactions.value.find(value => value.id === route.params.id)); const accountId = ref(''); const title = ref(''); const amount = ref<number | null>(null); const type = ref<TransactionType>('expense'); const category = ref('Other'); const date = ref(''); const note = ref(''); const error = ref('')
watch(item, (value) => { if (!value) return; accountId.value=value.accountId; title.value=value.title; amount.value=value.amount; type.value=value.type; category.value=value.category; date.value=value.date.slice(0,10); note.value=value.note ?? '' }, { immediate: true })
async function save() { if (!item.value || !amount.value) return; try { await finance.updateTransaction(item.value.id, { accountId: accountId.value, title: title.value, amount: amount.value, type: type.value, category: category.value, transactionDate: new Date(`${date.value}T12:00:00+07:00`).toISOString(), note: note.value }); await navigateTo('/transactions') } catch (cause) { error.value=(cause as { data?: { message?: string } })?.data?.message ?? 'Could not update entry' } }
async function remove() { if (!item.value || !confirm('Delete this entry?')) return; await finance.deleteTransaction(item.value.id); await navigateTo('/transactions') }
onMounted(() => finance.refresh().catch(() => undefined))
</script>
<template><main class="page"><NuxtLink to="/transactions" class="text-link">← History</NuxtLink><template v-if="item"><div class="eyebrow" style="margin-top:26px">Edit entry</div><h1 class="display">{{ item.title }}</h1><form class="form" @submit.prevent="save"><div class="toolbar"><button v-for="value in ['expense','income']" :key="value" type="button" class="pill" :class="{ active: type === value }" @click="type = value as TransactionType">{{ value }}</button></div><div class="field"><label>Account</label><select v-model="accountId"><option v-for="account in finance.accounts.value.filter(a => !a.isArchived || a.id === accountId)" :key="account.id" :value="account.id">{{ account.name }}</option></select></div><div class="field"><label>Title</label><input v-model.trim="title" required></div><div class="grid-2"><div class="field"><label>Amount</label><input v-model.number="amount" type="number" min="0.01" step="0.01"></div><div class="field"><label>Date</label><input v-model="date" type="date"></div></div><div class="field"><label>Category</label><input v-model.trim="category"></div><div class="field"><label>Note</label><input v-model="note"></div><p v-if="error" class="notice error">{{ error }}</p><button class="button accent">Save changes</button><button type="button" class="button danger" @click="remove">Delete entry</button></form></template><div v-else class="empty">Entry not found.</div></main></template>

