<script setup lang="ts">
import type { TransactionType } from '~/types/finance'
const finance = useFinance(); const type = ref<TransactionType>('expense'); const accountId = ref(''); const title = ref(''); const amount = ref<number | null>(null); const category = ref('Food'); const date = ref(new Date().toISOString().slice(0, 10)); const note = ref(''); const error = ref(''); const saving = ref(false)
const categories = computed(() => type.value === 'income' ? ['Salary','Bonus','Interest','Gift','Other'] : ['Food','Bills','Transport','Home','Health','Shopping','Other'])
watch(type, () => { category.value = categories.value[0] ?? 'Other' })
async function save() { if (!amount.value) return; saving.value = true; error.value = ''; try { await finance.createTransaction({ accountId: accountId.value, title: title.value, amount: amount.value, type: type.value, category: category.value, transactionDate: new Date(`${date.value}T12:00:00+07:00`).toISOString(), note: note.value }); await navigateTo('/transactions') } catch (cause) { error.value = (cause as { data?: { message?: string } })?.data?.message ?? 'Could not save entry' } finally { saving.value = false } }
onMounted(async () => { await finance.refresh().catch(() => undefined); accountId.value ||= finance.accounts.value.find(a => !a.isArchived)?.id ?? '' })
</script>
<template><main class="page"><NuxtLink to="/transactions" class="text-link">← History</NuxtLink><div class="eyebrow" style="margin-top:26px">A line in the ledger</div><h1 class="display">Add money.</h1><form class="form" @submit.prevent="save"><div class="toolbar"><button v-for="item in ['expense','income']" :key="item" type="button" class="pill" :class="{ active: type === item }" @click="type = item as TransactionType">{{ item }}</button><NuxtLink to="/transfers/new" class="pill">transfer →</NuxtLink></div><div v-if="!finance.accounts.value.filter(a => !a.isArchived).length" class="notice error">Create an account before adding an entry. <NuxtLink to="/accounts" class="text-link">Open accounts</NuxtLink></div><template v-else><div class="field"><label>Account</label><select v-model="accountId" required><option v-for="account in finance.accounts.value.filter(a => !a.isArchived)" :key="account.id" :value="account.id">{{ account.name }}</option></select></div><div class="field"><label>What was it?</label><input v-model.trim="title" placeholder="Coffee, rent, salary…" required></div><div class="grid-2"><div class="field"><label>Amount</label><input v-model.number="amount" type="number" min="0.01" step="0.01" required></div><div class="field"><label>Date</label><input v-model="date" type="date" required></div></div><div class="field"><label>Category</label><select v-model="category"><option v-for="item in categories" :key="item">{{ item }}</option></select></div><div class="field"><label>Note</label><input v-model="note" placeholder="Optional"></div><p v-if="error" class="notice error">{{ error }}</p><button class="button accent button-block" :disabled="saving">{{ saving ? 'Saving…' : 'Save entry' }}</button></template></form></main></template>
