<script setup lang="ts">
const route = useRoute(); const finance = useFinance(); const item = computed(() => finance.transfers.value.find(value => value.id === route.params.id)); const fromAccountId = ref(''); const toAccountId = ref(''); const amount = ref<number | null>(null); const date = ref(''); const note = ref(''); const error = ref('')
watch(item, (value) => { if (!value) return; fromAccountId.value = value.fromAccountId; toAccountId.value = value.toAccountId; amount.value = value.amount; date.value = value.date.slice(0, 10); note.value = value.note ?? '' }, { immediate: true })
async function save() { if (!item.value || !amount.value) return; try { await finance.updateTransfer(item.value.id, { fromAccountId: fromAccountId.value, toAccountId: toAccountId.value, amount: amount.value, transferDate: new Date(`${date.value}T12:00:00+07:00`).toISOString(), note: note.value }); await navigateTo('/transactions') } catch (cause) { error.value = (cause as { data?: { message?: string } })?.data?.message ?? 'Could not update transfer' } }
async function remove() { if (!item.value || !confirm('Delete this transfer?')) return; await finance.deleteTransfer(item.value.id); await navigateTo('/transactions') }
onMounted(() => finance.refresh().catch(() => undefined))
</script>
<template><main class="page"><NuxtLink to="/transactions" class="text-link">← History</NuxtLink><template v-if="item"><div class="eyebrow" style="margin-top:26px">Transfer</div><h1 class="display">Edit movement.</h1><form class="form" @submit.prevent="save"><div class="transfer-route"><div class="field"><label>From</label><select v-model="fromAccountId"><option v-for="account in finance.accounts.value.filter(a => !a.isArchived)" :key="account.id" :value="account.id">{{ account.name }}</option></select></div><span>→</span><div class="field"><label>To</label><select v-model="toAccountId"><option v-for="account in finance.accounts.value.filter(a => !a.isArchived)" :key="account.id" :value="account.id">{{ account.name }}</option></select></div></div><div class="grid-2"><div class="field"><label>Amount</label><input v-model.number="amount" type="number" min="0.01" step="0.01"></div><div class="field"><label>Date</label><input v-model="date" type="date"></div></div><div class="field"><label>Note</label><input v-model="note"></div><p v-if="error" class="notice error">{{ error }}</p><button class="button accent">Save changes</button><button type="button" class="button danger" @click="remove">Delete transfer</button></form></template><div v-else class="empty">Transfer not found.</div></main></template>

