<script setup lang="ts">
import type { AccountType } from '~/types/finance'
const finance = useFinance()
const showForm = ref(false); const name = ref(''); const type = ref<AccountType>('bank'); const openingBalance = ref(0); const saving = ref(false); const error = ref('')
const money = (value: number) => new Intl.NumberFormat('th-TH', { style: 'currency', currency: 'THB' }).format(value)
async function save() { saving.value = true; error.value = ''; try { await finance.createAccount({ name: name.value, type: type.value, openingBalance: openingBalance.value }); name.value = ''; openingBalance.value = 0; showForm.value = false } catch (cause) { error.value = (cause as { data?: { message?: string } })?.data?.message ?? 'Could not create account' } finally { saving.value = false } }
async function archive(id: string, archived: boolean) { await finance.updateAccount(id, { isArchived: !archived }) }
onMounted(() => finance.refresh().catch(() => undefined))
</script>
<template><main class="page"><div class="topline"><div><div class="eyebrow">Where money rests</div><h1 class="display">Accounts.</h1></div><button class="button accent" @click="showForm = !showForm">{{ showForm ? 'Close' : '+ Account' }}</button></div><section class="balance-card"><div class="balance-label">Across active accounts</div><div class="balance">{{ money(finance.totalBalance.value) }}</div><div class="balance-meta"><span>{{ finance.accounts.value.filter(a => !a.isArchived).length }} active accounts</span></div></section><form v-if="showForm" class="card form" @submit.prevent="save"><h2 class="section-title">Add an account</h2><div class="field"><label>Name</label><input v-model.trim="name" placeholder="Everyday bank, Cash…" required></div><div class="grid-2"><div class="field"><label>Type</label><select v-model="type"><option value="cash">Cash</option><option value="bank">Bank</option><option value="ewallet">e-Wallet</option><option value="other">Other</option></select></div><div class="field"><label>Opening balance</label><input v-model.number="openingBalance" type="number" step="0.01"></div></div><p v-if="error" class="notice error">{{ error }}</p><button class="button accent" :disabled="saving">{{ saving ? 'Saving…' : 'Save account' }}</button></form><div class="section-head"><h2 class="section-title">Your accounts</h2><NuxtLink to="/transfers/new" class="text-link">Move money →</NuxtLink></div><div v-if="finance.error.value" class="notice error">{{ finance.error.value }}</div><section class="account-list"><article v-for="account in finance.accounts.value" :key="account.id" class="account-row" :class="{ archived: account.isArchived }"><div class="account-glyph">{{ account.type === 'cash' ? '฿' : account.type === 'bank' ? '▦' : account.type === 'ewallet' ? '◫' : '○' }}</div><div class="transaction-copy"><strong>{{ account.name }}</strong><small>{{ account.type }} · {{ account.isArchived ? 'Archived' : 'Active' }}</small></div><div class="account-amount"><strong>{{ money(account.balance) }}</strong><div class="row-actions"><NuxtLink :to="`/accounts/${account.id}`" class="text-link">Edit</NuxtLink><button class="text-link" @click="archive(account.id, account.isArchived)">{{ account.isArchived ? 'Restore' : 'Archive' }}</button></div></div></article></section></main></template>
